"""Added category column to post

Revision ID: a7c13ac79068
Revises: 
Create Date: 2025-03-23 12:03:41.448445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c13ac79068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('pending__post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
